///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GBT_87
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GBT_87Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3a9d4bf8-d7f6-4d1a-af20-69a773da08cd")]
    public partial class GBT_87Repository : RepoGenBaseFolder
    {
        static GBT_87Repository instance = new GBT_87Repository();
        GBT_87RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        GBT_87RepositoryFolders.HọcLiệuSachMềmAppFolder _họcliệusachmềm;
        GBT_87RepositoryFolders.HọcLiệuSachMềm1AppFolder _họcliệusachmềm1;

        /// <summary>
        /// Gets the singleton class instance representing the GBT_87Repository element repository.
        /// </summary>
        [RepositoryFolder("3a9d4bf8-d7f6-4d1a-af20-69a773da08cd")]
        public static GBT_87Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GBT_87Repository() 
            : base("GBT_87Repository", "/", null, 0, false, "3a9d4bf8-d7f6-4d1a-af20-69a773da08cd", ".\\RepositoryImages\\GBT_87Repository3a9d4bf8.rximgres")
        {
            _applicationundertest = new GBT_87RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _họcliệusachmềm = new GBT_87RepositoryFolders.HọcLiệuSachMềmAppFolder(this);
            _họcliệusachmềm1 = new GBT_87RepositoryFolders.HọcLiệuSachMềm1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3a9d4bf8-d7f6-4d1a-af20-69a773da08cd")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("3ad2b8bd-d431-43f4-86b5-9bcecc105c49")]
        public virtual GBT_87RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The HọcLiệuSachMềm folder.
        /// </summary>
        [RepositoryFolder("6969b249-46b0-4c20-b7bf-e634f6d26109")]
        public virtual GBT_87RepositoryFolders.HọcLiệuSachMềmAppFolder HọcLiệuSachMềm
        {
            get { return _họcliệusachmềm; }
        }

        /// <summary>
        /// The HọcLiệuSachMềm1 folder.
        /// </summary>
        [RepositoryFolder("546e4c22-daef-4c70-94bf-9488dccbc77f")]
        public virtual GBT_87RepositoryFolders.HọcLiệuSachMềm1AppFolder HọcLiệuSachMềm1
        {
            get { return _họcliệusachmềm1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class GBT_87RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("3ad2b8bd-d431-43f4-86b5-9bcecc105c49")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, true, "3ad2b8bd-d431-43f4-86b5-9bcecc105c49", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3ad2b8bd-d431-43f4-86b5-9bcecc105c49")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3ad2b8bd-d431-43f4-86b5-9bcecc105c49")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The HọcLiệuSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("6969b249-46b0-4c20-b7bf-e634f6d26109")]
        public partial class HọcLiệuSachMềmAppFolder : RepoGenBaseFolder
        {
            GBT_87RepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder _httpshoclieusachmemvnquestionset;
            RepoItemInfo _giaobaitậpInfo;
            RepoItemInfo _spantag1Info;
            RepoItemInfo _spantag3Info;
            RepoItemInfo _javascriptvoid0Info;
            RepoItemInfo _toasterrortoastngtriggerngtriggerInfo;

            /// <summary>
            /// Creates a new HọcLiệuSachMềm  folder.
            /// </summary>
            public HọcLiệuSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HọcLiệuSachMềm", "/dom[@domain='hoclieu.sachmem.vn']", parentFolder, 30000, null, false, "6969b249-46b0-4c20-b7bf-e634f6d26109", "")
            {
                _httpshoclieusachmemvnquestionset = new GBT_87RepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder(this);
                _giaobaitậpInfo = new RepoItemInfo(this, "GiaoBaiTập", "body/tag[@tagname='app-root']/div[2]//tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div[1]/div[1]/div[2]/a[@href='javascript:void(0)']/span[@innertext='Giao bài tập']", 30000, null, "cffa8d52-7230-43fb-8545-78b73bee59f4");
                _spantag1Info = new RepoItemInfo(this, "SpanTag1", "body//tag[@tagname='bs-calendar-layout']/div[2]/table/tbody/tr[1]/td[3]/span[@innertext='1']", 30000, null, "a3e2d8b2-a950-48a1-8619-48e8614ae0c8");
                _spantag3Info = new RepoItemInfo(this, "SpanTag3", "body//tag[@tagname='bs-calendar-layout']/div[2]/table/tbody/tr[1]/td[5]/span[@innertext='3']", 30000, null, "1168d4ee-8003-4c47-946b-923cc71261c2");
                _javascriptvoid0Info = new RepoItemInfo(this, "JavascriptVoid0", "body/tag[@tagname='app-root']/div[2]/div//tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div[1]/div[1]/div[2]/a[@href='javascript:void(0)']", 30000, null, "1834d588-11d4-4878-a683-e4c694e2a0f0");
                _toasterrortoastngtriggerngtriggerInfo = new RepoItemInfo(this, "ToastErrorToastNgTriggerNgTrigger", ".//div[#'toast-container']/div", 30000, null, "d82fb8ff-3986-48f1-a48e-88e14fbf5fe0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6969b249-46b0-4c20-b7bf-e634f6d26109")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6969b249-46b0-4c20-b7bf-e634f6d26109")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GiaoBaiTập item.
            /// </summary>
            [RepositoryItem("cffa8d52-7230-43fb-8545-78b73bee59f4")]
            public virtual Ranorex.SpanTag GiaoBaiTập
            {
                get
                {
                    return _giaobaitậpInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GiaoBaiTập item info.
            /// </summary>
            [RepositoryItemInfo("cffa8d52-7230-43fb-8545-78b73bee59f4")]
            public virtual RepoItemInfo GiaoBaiTậpInfo
            {
                get
                {
                    return _giaobaitậpInfo;
                }
            }

            /// <summary>
            /// The SpanTag1 item.
            /// </summary>
            [RepositoryItem("a3e2d8b2-a950-48a1-8619-48e8614ae0c8")]
            public virtual Ranorex.SpanTag SpanTag1
            {
                get
                {
                    return _spantag1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag1 item info.
            /// </summary>
            [RepositoryItemInfo("a3e2d8b2-a950-48a1-8619-48e8614ae0c8")]
            public virtual RepoItemInfo SpanTag1Info
            {
                get
                {
                    return _spantag1Info;
                }
            }

            /// <summary>
            /// The SpanTag3 item.
            /// </summary>
            [RepositoryItem("1168d4ee-8003-4c47-946b-923cc71261c2")]
            public virtual Ranorex.SpanTag SpanTag3
            {
                get
                {
                    return _spantag3Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag3 item info.
            /// </summary>
            [RepositoryItemInfo("1168d4ee-8003-4c47-946b-923cc71261c2")]
            public virtual RepoItemInfo SpanTag3Info
            {
                get
                {
                    return _spantag3Info;
                }
            }

            /// <summary>
            /// The JavascriptVoid0 item.
            /// </summary>
            [RepositoryItem("1834d588-11d4-4878-a683-e4c694e2a0f0")]
            public virtual Ranorex.ATag JavascriptVoid0
            {
                get
                {
                    return _javascriptvoid0Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The JavascriptVoid0 item info.
            /// </summary>
            [RepositoryItemInfo("1834d588-11d4-4878-a683-e4c694e2a0f0")]
            public virtual RepoItemInfo JavascriptVoid0Info
            {
                get
                {
                    return _javascriptvoid0Info;
                }
            }

            /// <summary>
            /// The ToastErrorToastNgTriggerNgTrigger item.
            /// </summary>
            [RepositoryItem("d82fb8ff-3986-48f1-a48e-88e14fbf5fe0")]
            public virtual Ranorex.DivTag ToastErrorToastNgTriggerNgTrigger
            {
                get
                {
                    return _toasterrortoastngtriggerngtriggerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ToastErrorToastNgTriggerNgTrigger item info.
            /// </summary>
            [RepositoryItemInfo("d82fb8ff-3986-48f1-a48e-88e14fbf5fe0")]
            public virtual RepoItemInfo ToastErrorToastNgTriggerNgTriggerInfo
            {
                get
                {
                    return _toasterrortoastngtriggerngtriggerInfo;
                }
            }

            /// <summary>
            /// The HttpsHoclieuSachmemVnQuestionSet folder.
            /// </summary>
            [RepositoryFolder("60ff5ab4-2245-4a91-b34d-1ed24cc37372")]
            public virtual GBT_87RepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder HttpsHoclieuSachmemVnQuestionSet
            {
                get { return _httpshoclieusachmemvnquestionset; }
            }
        }

        /// <summary>
        /// The HttpsHoclieuSachmemVnQuestionSetFolder folder.
        /// </summary>
        [RepositoryFolder("60ff5ab4-2245-4a91-b34d-1ed24cc37372")]
        public partial class HttpsHoclieuSachmemVnQuestionSetFolder : RepoGenBaseFolder
        {
            RepoItemInfo _submitInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _ngoptionngoptionmarkedInfo;
            RepoItemInfo _nginputInfo;
            RepoItemInfo _ngarrowwrapperInfo;

            /// <summary>
            /// Creates a new HttpsHoclieuSachmemVnQuestionSet  folder.
            /// </summary>
            public HttpsHoclieuSachmemVnQuestionSetFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsHoclieuSachmemVnQuestionSet", ".//div[#'createAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b18b248150cd8b90656fe/5a4b18b248150cd8b9065701/preview']", parentFolder, 30000, null, false, "60ff5ab4-2245-4a91-b34d-1ed24cc37372", "")
            {
                _submitInfo = new RepoItemInfo(this, "Submit", "?/?/input[@type='submit']", 30000, null, "10a1a154-f4eb-4fe3-89b1-6a5d4ae55493");
                _textInfo = new RepoItemInfo(this, "Text", "div[1]/div[10]/?/?/input[@type='text']", 30000, null, "604b6b65-7bc9-4456-88f1-2964607e1ee5");
                _text1Info = new RepoItemInfo(this, "Text1", "div[1]/div[10]/?/?/input[@value='11/04/2019']", 30000, null, "b7bc923b-1f18-47a7-93b4-6365bab6b54a");
                _ngoptionngoptionmarkedInfo = new RepoItemInfo(this, "NgOptionNgOptionMarked", "div[1]/div[3]/?/?/tag[@tagname='ng-dropdown-panel']/div/div[2]/div", 30000, null, "35790c1e-bd33-4ecf-a952-5cb8b3a87b6e");
                _nginputInfo = new RepoItemInfo(this, "NgInput", "div[1]/div[3]/tag[@tagname='ng-select']/div/div/div[2]", 30000, null, "5201eb2b-f88d-4787-bc9d-458ffa2bb609");
                _ngarrowwrapperInfo = new RepoItemInfo(this, "NgArrowWrapper", "div[1]/div[3]//span", 30000, null, "0e4f54af-cb81-4ab8-8a29-3e46c4b6612d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("60ff5ab4-2245-4a91-b34d-1ed24cc37372")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("60ff5ab4-2245-4a91-b34d-1ed24cc37372")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("10a1a154-f4eb-4fe3-89b1-6a5d4ae55493")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("10a1a154-f4eb-4fe3-89b1-6a5d4ae55493")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("604b6b65-7bc9-4456-88f1-2964607e1ee5")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("604b6b65-7bc9-4456-88f1-2964607e1ee5")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("b7bc923b-1f18-47a7-93b4-6365bab6b54a")]
            public virtual Ranorex.InputTag Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("b7bc923b-1f18-47a7-93b4-6365bab6b54a")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarked item.
            /// </summary>
            [RepositoryItem("35790c1e-bd33-4ecf-a952-5cb8b3a87b6e")]
            public virtual Ranorex.DivTag NgOptionNgOptionMarked
            {
                get
                {
                    return _ngoptionngoptionmarkedInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarked item info.
            /// </summary>
            [RepositoryItemInfo("35790c1e-bd33-4ecf-a952-5cb8b3a87b6e")]
            public virtual RepoItemInfo NgOptionNgOptionMarkedInfo
            {
                get
                {
                    return _ngoptionngoptionmarkedInfo;
                }
            }

            /// <summary>
            /// The NgInput item.
            /// </summary>
            [RepositoryItem("5201eb2b-f88d-4787-bc9d-458ffa2bb609")]
            public virtual Ranorex.DivTag NgInput
            {
                get
                {
                    return _nginputInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgInput item info.
            /// </summary>
            [RepositoryItemInfo("5201eb2b-f88d-4787-bc9d-458ffa2bb609")]
            public virtual RepoItemInfo NgInputInfo
            {
                get
                {
                    return _nginputInfo;
                }
            }

            /// <summary>
            /// The NgArrowWrapper item.
            /// </summary>
            [RepositoryItem("0e4f54af-cb81-4ab8-8a29-3e46c4b6612d")]
            public virtual Ranorex.SpanTag NgArrowWrapper
            {
                get
                {
                    return _ngarrowwrapperInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The NgArrowWrapper item info.
            /// </summary>
            [RepositoryItemInfo("0e4f54af-cb81-4ab8-8a29-3e46c4b6612d")]
            public virtual RepoItemInfo NgArrowWrapperInfo
            {
                get
                {
                    return _ngarrowwrapperInfo;
                }
            }
        }

        /// <summary>
        /// The HọcLiệuSachMềm1AppFolder folder.
        /// </summary>
        [RepositoryFolder("546e4c22-daef-4c70-94bf-9488dccbc77f")]
        public partial class HọcLiệuSachMềm1AppFolder : RepoGenBaseFolder
        {
            GBT_87RepositoryFolders.CreateAssignmentModal1Folder _createassignmentmodal1;
            RepoItemInfo _javascriptvoid0Info;
            RepoItemInfo _spantag3Info;
            RepoItemInfo _spantag5Info;
            RepoItemInfo _somedivtagInfo;

            /// <summary>
            /// Creates a new HọcLiệuSachMềm1  folder.
            /// </summary>
            public HọcLiệuSachMềm1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("HọcLiệuSachMềm1", "/dom[6]", parentFolder, 30000, null, false, "546e4c22-daef-4c70-94bf-9488dccbc77f", "")
            {
                _createassignmentmodal1 = new GBT_87RepositoryFolders.CreateAssignmentModal1Folder(this);
                _javascriptvoid0Info = new RepoItemInfo(this, "JavascriptVoid0", "body/tag[@tagname='app-root']/div[2]/div//tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div[1]/div[1]/div[2]/a[@href='javascript:void(0)']", 30000, null, "120de90e-c757-4b50-9592-e2ace132a4c5");
                _spantag3Info = new RepoItemInfo(this, "SpanTag3", "body//tag[@tagname='bs-calendar-layout']/div[2]/table/tbody/tr[1]/td[5]/span[@innertext='3']", 30000, null, "ec60b55d-22fc-454b-abeb-05e14fcfbb51");
                _spantag5Info = new RepoItemInfo(this, "SpanTag5", "body//tag[@tagname='bs-calendar-layout']/div[2]/table/tbody/tr[1]/td[7]/span[@innertext='5']", 30000, null, "d768c045-aaad-4ccf-8654-c4d265badb65");
                _somedivtagInfo = new RepoItemInfo(this, "SomeDivTag", ".//div[#'toast-container']/?/?/div", 30000, null, "9f9bd990-ed8e-4312-a304-fcbf109629aa");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("546e4c22-daef-4c70-94bf-9488dccbc77f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("546e4c22-daef-4c70-94bf-9488dccbc77f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JavascriptVoid0 item.
            /// </summary>
            [RepositoryItem("120de90e-c757-4b50-9592-e2ace132a4c5")]
            public virtual Ranorex.ATag JavascriptVoid0
            {
                get
                {
                    return _javascriptvoid0Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The JavascriptVoid0 item info.
            /// </summary>
            [RepositoryItemInfo("120de90e-c757-4b50-9592-e2ace132a4c5")]
            public virtual RepoItemInfo JavascriptVoid0Info
            {
                get
                {
                    return _javascriptvoid0Info;
                }
            }

            /// <summary>
            /// The SpanTag3 item.
            /// </summary>
            [RepositoryItem("ec60b55d-22fc-454b-abeb-05e14fcfbb51")]
            public virtual Ranorex.SpanTag SpanTag3
            {
                get
                {
                    return _spantag3Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag3 item info.
            /// </summary>
            [RepositoryItemInfo("ec60b55d-22fc-454b-abeb-05e14fcfbb51")]
            public virtual RepoItemInfo SpanTag3Info
            {
                get
                {
                    return _spantag3Info;
                }
            }

            /// <summary>
            /// The SpanTag5 item.
            /// </summary>
            [RepositoryItem("d768c045-aaad-4ccf-8654-c4d265badb65")]
            public virtual Ranorex.SpanTag SpanTag5
            {
                get
                {
                    return _spantag5Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag5 item info.
            /// </summary>
            [RepositoryItemInfo("d768c045-aaad-4ccf-8654-c4d265badb65")]
            public virtual RepoItemInfo SpanTag5Info
            {
                get
                {
                    return _spantag5Info;
                }
            }

            /// <summary>
            /// The SomeDivTag item.
            /// </summary>
            [RepositoryItem("9f9bd990-ed8e-4312-a304-fcbf109629aa")]
            public virtual Ranorex.DivTag SomeDivTag
            {
                get
                {
                    return _somedivtagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeDivTag item info.
            /// </summary>
            [RepositoryItemInfo("9f9bd990-ed8e-4312-a304-fcbf109629aa")]
            public virtual RepoItemInfo SomeDivTagInfo
            {
                get
                {
                    return _somedivtagInfo;
                }
            }

            /// <summary>
            /// The CreateAssignmentModal1 folder.
            /// </summary>
            [RepositoryFolder("49e3852c-8f17-4ea6-b8e3-68293527019b")]
            public virtual GBT_87RepositoryFolders.CreateAssignmentModal1Folder CreateAssignmentModal1
            {
                get { return _createassignmentmodal1; }
            }
        }

        /// <summary>
        /// The CreateAssignmentModal1Folder folder.
        /// </summary>
        [RepositoryFolder("49e3852c-8f17-4ea6-b8e3-68293527019b")]
        public partial class CreateAssignmentModal1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _createassignmentmodalInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _ngoptionngoptionmarkedInfo;
            RepoItemInfo _nginputInfo;

            /// <summary>
            /// Creates a new CreateAssignmentModal1  folder.
            /// </summary>
            public CreateAssignmentModal1Folder(RepoGenBaseFolder parentFolder) :
                    base("CreateAssignmentModal1", ".//div[#'createAssignmentModal']", parentFolder, 30000, null, false, "49e3852c-8f17-4ea6-b8e3-68293527019b", "")
            {
                _createassignmentmodalInfo = new RepoItemInfo(this, "CreateAssignmentModal", "", 30000, null, "c0fcce4d-228c-458b-9648-a93cca9b2f9e");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b18bc48150cd8b90657e7/5a4b18bc48150cd8b90657ea/preview']/?/?/input[@type='submit']", 30000, null, "1d0358e1-5740-4bd3-8225-629cfe66cfeb");
                _textInfo = new RepoItemInfo(this, "Text", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b18bc48150cd8b90657e7/5a4b18bc48150cd8b90657ea/preview']/div[1]/div[10]/?/?/input[@type='text']", 30000, null, "dd7582f4-c80b-4ab4-8392-f353f747da96");
                _text1Info = new RepoItemInfo(this, "Text1", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b18bc48150cd8b90657e7/5a4b18bc48150cd8b90657ea/preview']/div[1]/div[10]/?/?/input[@value='17/04/2019']", 30000, null, "71b5f607-d828-43ff-a62f-4aa8248d7669");
                _ngoptionngoptionmarkedInfo = new RepoItemInfo(this, "NgOptionNgOptionMarked", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b18bc48150cd8b90657e7/5a4b18bc48150cd8b90657ea/preview']/div[1]/div[3]/?/?/tag[@tagname='ng-dropdown-panel']/div/div[2]/div", 30000, null, "d5a7c9b9-2962-4641-b243-efbaaecd4186");
                _nginputInfo = new RepoItemInfo(this, "NgInput", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b18bc48150cd8b90657e7/5a4b18bc48150cd8b90657ea/preview']/div[1]/div[3]/tag[@tagname='ng-select']/div/div/div[2]", 30000, null, "85adefa8-e3c3-49d7-93d1-b69e2320baa5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("49e3852c-8f17-4ea6-b8e3-68293527019b")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("49e3852c-8f17-4ea6-b8e3-68293527019b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateAssignmentModal item.
            /// </summary>
            [RepositoryItem("c0fcce4d-228c-458b-9648-a93cca9b2f9e")]
            public virtual Ranorex.DivTag CreateAssignmentModal
            {
                get
                {
                    return _createassignmentmodalInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CreateAssignmentModal item info.
            /// </summary>
            [RepositoryItemInfo("c0fcce4d-228c-458b-9648-a93cca9b2f9e")]
            public virtual RepoItemInfo CreateAssignmentModalInfo
            {
                get
                {
                    return _createassignmentmodalInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("1d0358e1-5740-4bd3-8225-629cfe66cfeb")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("1d0358e1-5740-4bd3-8225-629cfe66cfeb")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("dd7582f4-c80b-4ab4-8392-f353f747da96")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("dd7582f4-c80b-4ab4-8392-f353f747da96")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("71b5f607-d828-43ff-a62f-4aa8248d7669")]
            public virtual Ranorex.InputTag Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("71b5f607-d828-43ff-a62f-4aa8248d7669")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarked item.
            /// </summary>
            [RepositoryItem("d5a7c9b9-2962-4641-b243-efbaaecd4186")]
            public virtual Ranorex.DivTag NgOptionNgOptionMarked
            {
                get
                {
                    return _ngoptionngoptionmarkedInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarked item info.
            /// </summary>
            [RepositoryItemInfo("d5a7c9b9-2962-4641-b243-efbaaecd4186")]
            public virtual RepoItemInfo NgOptionNgOptionMarkedInfo
            {
                get
                {
                    return _ngoptionngoptionmarkedInfo;
                }
            }

            /// <summary>
            /// The NgInput item.
            /// </summary>
            [RepositoryItem("85adefa8-e3c3-49d7-93d1-b69e2320baa5")]
            public virtual Ranorex.DivTag NgInput
            {
                get
                {
                    return _nginputInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgInput item info.
            /// </summary>
            [RepositoryItemInfo("85adefa8-e3c3-49d7-93d1-b69e2320baa5")]
            public virtual RepoItemInfo NgInputInfo
            {
                get
                {
                    return _nginputInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
