///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GBT_87
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenBrowser recording.
    /// </summary>
    [TestModule("a4a3694c-a7a3-4915-a3ae-6c9d9af97f60", ModuleType.Recording, 1)]
    public partial class OpenBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GBT_87Repository repository.
        /// </summary>
        public static GBT_87Repository repo = GBT_87Repository.Instance;

        static OpenBrowser instance = new OpenBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenBrowser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenBrowser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://hoclieu.sachmem.vn/question_set/5a4b18bc48150cd8b90657e7/5a4b18bc48150cd8b90657ea/preview' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://hoclieu.sachmem.vn/question_set/5a4b18bc48150cd8b90657e7/5a4b18bc48150cd8b90657ea/preview", "chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm1.JavascriptVoid0' at 25;27.", repo.HọcLiệuSachMềm1.JavascriptVoid0Info, new RecordItemIndex(1));
            repo.HọcLiệuSachMềm1.JavascriptVoid0.Click("25;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm1.CreateAssignmentModal1.NgInput' at 140;8.", repo.HọcLiệuSachMềm1.CreateAssignmentModal1.NgInputInfo, new RecordItemIndex(2));
            repo.HọcLiệuSachMềm1.CreateAssignmentModal1.NgInput.Click("140;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm1.CreateAssignmentModal1.NgOptionNgOptionMarked' at 108;14.", repo.HọcLiệuSachMềm1.CreateAssignmentModal1.NgOptionNgOptionMarkedInfo, new RecordItemIndex(3));
            repo.HọcLiệuSachMềm1.CreateAssignmentModal1.NgOptionNgOptionMarked.Click("108;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(4));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm1.CreateAssignmentModal1.Text' at 100;13.", repo.HọcLiệuSachMềm1.CreateAssignmentModal1.TextInfo, new RecordItemIndex(5));
            repo.HọcLiệuSachMềm1.CreateAssignmentModal1.Text.Click("100;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm1.SpanTag3' at 11;15.", repo.HọcLiệuSachMềm1.SpanTag3Info, new RecordItemIndex(6));
            repo.HọcLiệuSachMềm1.SpanTag3.Click("11;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm1.CreateAssignmentModal1.Text1' at 93;4.", repo.HọcLiệuSachMềm1.CreateAssignmentModal1.Text1Info, new RecordItemIndex(7));
            repo.HọcLiệuSachMềm1.CreateAssignmentModal1.Text1.Click("93;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'HọcLiệuSachMềm1.SpanTag5' at 22;8.", repo.HọcLiệuSachMềm1.SpanTag5Info, new RecordItemIndex(8));
            repo.HọcLiệuSachMềm1.SpanTag5.DoubleClick("22;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm1.CreateAssignmentModal1.Submit' at 16;13.", repo.HọcLiệuSachMềm1.CreateAssignmentModal1.SubmitInfo, new RecordItemIndex(9));
            repo.HọcLiệuSachMềm1.CreateAssignmentModal1.Submit.Click("16;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'HọcLiệuSachMềm1.SomeDivTag'.", repo.HọcLiệuSachMềm1.SomeDivTagInfo, new RecordItemIndex(10));
            Validate.Exists(repo.HọcLiệuSachMềm1.SomeDivTagInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
