///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GBT_36
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenBrowser recording.
    /// </summary>
    [TestModule("0a339ac1-9aea-481c-9d77-574f122d3491", ModuleType.Recording, 1)]
    public partial class OpenBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GBT_36Repository repository.
        /// </summary>
        public static GBT_36Repository repo = GBT_36Repository.Instance;

        static OpenBrowser instance = new OpenBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenBrowser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenBrowser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://hoclieu.sachmem.vn/question_set/5a4b18bc48150cd8b90657e7/5a4b18bc48150cd8b90657ea/preview' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://hoclieu.sachmem.vn/question_set/5a4b18bc48150cd8b90657e7/5a4b18bc48150cd8b90657ea/preview", "chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.GiaoBaiTập' at 8;18.", repo.HọcLiệuSachMềm.GiaoBaiTậpInfo, new RecordItemIndex(1));
            repo.HọcLiệuSachMềm.GiaoBaiTập.Click("8;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text' at 190;22.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TextInfo, new RecordItemIndex(2));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text.DoubleClick("190;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text' at 190;22.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TextInfo, new RecordItemIndex(3));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text.DoubleClick("190;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text' at 190;22.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TextInfo, new RecordItemIndex(4));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text.Click("190;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text' at 190;22.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TextInfo, new RecordItemIndex(5));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text.DoubleClick("190;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 16}{LShiftKey down}{# down}{LShiftKey up}52{LShiftKey down}{Back down}{Back up}#@##%#%@%{LShiftKey up}' with focus on 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text'.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TextInfo, new RecordItemIndex(6));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text.PressKeys("{Back 16}{LShiftKey down}{# down}{LShiftKey up}52{LShiftKey down}{Back down}{Back up}#@##%#%@%{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgArrowWrapper' at 6;8.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgArrowWrapperInfo, new RecordItemIndex(7));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgArrowWrapper.Click("6;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgOptionNgOptionMarked' at 147;18.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgOptionNgOptionMarkedInfo, new RecordItemIndex(8));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgOptionNgOptionMarked.Click("147;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.ModalBody' at 438;114.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.ModalBodyInfo, new RecordItemIndex(9));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.ModalBody.MoveTo("438;114");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.ModalBody' at 446;106.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.ModalBodyInfo, new RecordItemIndex(10));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.ModalBody.MoveTo("446;106");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.DivTagRow' at 421;32.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.DivTagRowInfo, new RecordItemIndex(11));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.DivTagRow.MoveTo("421;32");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number' at 125;11.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(12));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number.Click("125;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5' with focus on 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number'.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(13));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number.PressKeys("5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number1' at 111;7.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number1Info, new RecordItemIndex(14));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number1.Click("111;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '3' with focus on 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number1'.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number1Info, new RecordItemIndex(15));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number1.PressKeys("3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Submit' at 16;13.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.SubmitInfo, new RecordItemIndex(16));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Submit.Click("16;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'HọcLiệuSachMềm.DivTagGiaoBaiTậpThanhCong'.", repo.HọcLiệuSachMềm.DivTagGiaoBaiTậpThanhCongInfo, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.HọcLiệuSachMềm.DivTagGiaoBaiTậpThanhCongInfo, "Valid", "True");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
