///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Testing_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Testing_2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("13949ddb-9164-438c-a395-b3d6b9124318")]
    public partial class Testing_2Repository : RepoGenBaseFolder
    {
        static Testing_2Repository instance = new Testing_2Repository();
        Testing_2RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Testing_2RepositoryFolders.ExplorerAppFolder _explorer;
        Testing_2RepositoryFolders.BaiTậpThựcHanhKiểmThửMonINT31172AppFolder _baitậpthựchanhkiểmthửmonint31172;
        Testing_2RepositoryFolders.Explorer1AppFolder _explorer1;
        Testing_2RepositoryFolders.Test1AppFolder _test1;
        Testing_2RepositoryFolders.HọcLiệuSachMềmAppFolder _họcliệusachmềm;

        /// <summary>
        /// Gets the singleton class instance representing the Testing_2Repository element repository.
        /// </summary>
        [RepositoryFolder("13949ddb-9164-438c-a395-b3d6b9124318")]
        public static Testing_2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Testing_2Repository() 
            : base("Testing_2Repository", "/", null, 0, false, "13949ddb-9164-438c-a395-b3d6b9124318", ".\\RepositoryImages\\Testing_2Repository13949ddb.rximgres")
        {
            _applicationundertest = new Testing_2RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new Testing_2RepositoryFolders.ExplorerAppFolder(this);
            _baitậpthựchanhkiểmthửmonint31172 = new Testing_2RepositoryFolders.BaiTậpThựcHanhKiểmThửMonINT31172AppFolder(this);
            _explorer1 = new Testing_2RepositoryFolders.Explorer1AppFolder(this);
            _test1 = new Testing_2RepositoryFolders.Test1AppFolder(this);
            _họcliệusachmềm = new Testing_2RepositoryFolders.HọcLiệuSachMềmAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("13949ddb-9164-438c-a395-b3d6b9124318")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("08198c71-b9e0-4a1a-ba4c-a5d53f7dc602")]
        public virtual Testing_2RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("6172c81d-87f0-47d3-b4ed-73e888089259")]
        public virtual Testing_2RepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The BaiTậpThựcHanhKiểmThửMonINT31172 folder.
        /// </summary>
        [RepositoryFolder("fabfbad4-fbdf-4423-ae01-9214de260841")]
        public virtual Testing_2RepositoryFolders.BaiTậpThựcHanhKiểmThửMonINT31172AppFolder BaiTậpThựcHanhKiểmThửMonINT31172
        {
            get { return _baitậpthựchanhkiểmthửmonint31172; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("9e495441-8ba6-4947-b70c-f9461ad2c014")]
        public virtual Testing_2RepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }

        /// <summary>
        /// The Test1 folder.
        /// </summary>
        [RepositoryFolder("6855f39e-4fd4-4818-ada7-acd00519c5bd")]
        public virtual Testing_2RepositoryFolders.Test1AppFolder Test1
        {
            get { return _test1; }
        }

        /// <summary>
        /// The HọcLiệuSachMềm folder.
        /// </summary>
        [RepositoryFolder("82684236-7f96-41e0-98ad-b714a2aa6abd")]
        public virtual Testing_2RepositoryFolders.HọcLiệuSachMềmAppFolder HọcLiệuSachMềm
        {
            get { return _họcliệusachmềm; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Testing_2RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("08198c71-b9e0-4a1a-ba4c-a5d53f7dc602")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, true, "08198c71-b9e0-4a1a-ba4c-a5d53f7dc602", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("08198c71-b9e0-4a1a-ba4c-a5d53f7dc602")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("08198c71-b9e0-4a1a-ba4c-a5d53f7dc602")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("6172c81d-87f0-47d3-b4ed-73e888089259")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _googlechrome1runningwindowInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "6172c81d-87f0-47d3-b4ed-73e888089259", "")
            {
                _googlechrome1runningwindowInfo = new RepoItemInfo(this, "GoogleChrome1RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename~'^Google\\ Chrome\\ -\\ 1\\ running']", 30000, null, "c6dd1278-26a6-478d-9850-8ad5ba53993b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6172c81d-87f0-47d3-b4ed-73e888089259")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6172c81d-87f0-47d3-b4ed-73e888089259")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GoogleChrome1RunningWindow item.
            /// </summary>
            [RepositoryItem("c6dd1278-26a6-478d-9850-8ad5ba53993b")]
            public virtual Ranorex.Button GoogleChrome1RunningWindow
            {
                get
                {
                    return _googlechrome1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GoogleChrome1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("c6dd1278-26a6-478d-9850-8ad5ba53993b")]
            public virtual RepoItemInfo GoogleChrome1RunningWindowInfo
            {
                get
                {
                    return _googlechrome1runningwindowInfo;
                }
            }
        }

        /// <summary>
        /// The BaiTậpThựcHanhKiểmThửMonINT31172AppFolder folder.
        /// </summary>
        [RepositoryFolder("fabfbad4-fbdf-4423-ae01-9214de260841")]
        public partial class BaiTậpThựcHanhKiểmThửMonINT31172AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _facebookInfo;
            RepoItemInfo _paneInfo;

            /// <summary>
            /// Creates a new BaiTậpThựcHanhKiểmThửMonINT31172  folder.
            /// </summary>
            public BaiTậpThựcHanhKiểmThửMonINT31172AppFolder(RepoGenBaseFolder parentFolder) :
                    base("BaiTậpThựcHanhKiểmThửMonINT31172", "/form[@title~'^Bài\\ tập\\ thực\\ hành\\ kiểm\\ th']", parentFolder, 30000, null, true, "fabfbad4-fbdf-4423-ae01-9214de260841", "")
            {
                _facebookInfo = new RepoItemInfo(this, "Facebook", "container[@accessiblename~'^Bài\\ tập\\ thực\\ hành\\ kiểm\\ th']/container[@accessiblename='Google Chrome']//tabpage[@accessiblename='Facebook']", 30000, null, "6a6f8cbf-3fca-457a-876d-6b66134beeb0");
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename='Facebook - Google Chrome']/container[@accessiblename='Google Chrome']/container[2]/container[1]/container[@accessiblerole='Pane']/container[1]/container[2]", 30000, null, "d857e6fc-740e-4be0-83d2-2a5506d3531a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fabfbad4-fbdf-4423-ae01-9214de260841")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fabfbad4-fbdf-4423-ae01-9214de260841")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Facebook item.
            /// </summary>
            [RepositoryItem("6a6f8cbf-3fca-457a-876d-6b66134beeb0")]
            public virtual Ranorex.TabPage Facebook
            {
                get
                {
                    return _facebookInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Facebook item info.
            /// </summary>
            [RepositoryItemInfo("6a6f8cbf-3fca-457a-876d-6b66134beeb0")]
            public virtual RepoItemInfo FacebookInfo
            {
                get
                {
                    return _facebookInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("d857e6fc-740e-4be0-83d2-2a5506d3531a")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("d857e6fc-740e-4be0-83d2-2a5506d3531a")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("9e495441-8ba6-4947-b70c-f9461ad2c014")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/form[@processname='explorer' and @class='WorkerW' and @instance='0']", parentFolder, 30000, null, true, "9e495441-8ba6-4947-b70c-f9461ad2c014", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "?/?/list[@controlid='1']", 30000, null, "330d43d9-fadb-431a-84c9-c36ddcda0473");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9e495441-8ba6-4947-b70c-f9461ad2c014")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9e495441-8ba6-4947-b70c-f9461ad2c014")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("330d43d9-fadb-431a-84c9-c36ddcda0473")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("330d43d9-fadb-431a-84c9-c36ddcda0473")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }
        }

        /// <summary>
        /// The Test1AppFolder folder.
        /// </summary>
        [RepositoryFolder("6855f39e-4fd4-4818-ada7-acd00519c5bd")]
        public partial class Test1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _itemsviewInfo;

            /// <summary>
            /// Creates a new Test1  folder.
            /// </summary>
            public Test1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Test1", "/form[@title='Test 1']", parentFolder, 30000, null, true, "6855f39e-4fd4-4818-ada7-acd00519c5bd", "")
            {
                _itemsviewInfo = new RepoItemInfo(this, "ItemsView", "element[@class='ShellTabWindowClass']//element[@instance='1']/container[@caption='ShellView']/?/?/list[@accessiblename='Items View']", 30000, null, "54a1c2c0-2fcd-4fa9-8ff1-ec73252af791");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6855f39e-4fd4-4818-ada7-acd00519c5bd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6855f39e-4fd4-4818-ada7-acd00519c5bd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ItemsView item.
            /// </summary>
            [RepositoryItem("54a1c2c0-2fcd-4fa9-8ff1-ec73252af791")]
            public virtual Ranorex.List ItemsView
            {
                get
                {
                    return _itemsviewInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The ItemsView item info.
            /// </summary>
            [RepositoryItemInfo("54a1c2c0-2fcd-4fa9-8ff1-ec73252af791")]
            public virtual RepoItemInfo ItemsViewInfo
            {
                get
                {
                    return _itemsviewInfo;
                }
            }
        }

        /// <summary>
        /// The HọcLiệuSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("82684236-7f96-41e0-98ad-b714a2aa6abd")]
        public partial class HọcLiệuSachMềmAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _giaobaitậpInfo;
            RepoItemInfo _fafausersInfo;
            RepoItemInfo _divtagbạnchưacolớphọcInfo;

            /// <summary>
            /// Creates a new HọcLiệuSachMềm  folder.
            /// </summary>
            public HọcLiệuSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HọcLiệuSachMềm", "/dom[@domain='hoclieu.sachmem.vn']", parentFolder, 30000, null, false, "82684236-7f96-41e0-98ad-b714a2aa6abd", "")
            {
                _giaobaitậpInfo = new RepoItemInfo(this, "GiaoBaiTập", "body/tag[@tagname='app-root']/div[2]//tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div[1]/div[1]/div[2]/a[@href='javascript:void(0)']/span[@innertext='Giao bài tập']", 30000, null, "e6c4041b-816f-44df-9441-3e00afd7bfd6");
                _fafausersInfo = new RepoItemInfo(this, "FaFaUsers", "body/tag[@tagname='app-root']/div[2]//tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div[1]/div[1]/div[2]/a[@href='javascript:void(0)']/i", 30000, null, "85567aed-f504-4e7d-940c-7d5440a3e776");
                _divtagbạnchưacolớphọcInfo = new RepoItemInfo(this, "DivTagBạnChưaCoLớpHọc", ".//div[#'toast-container']/?/?/div[@innertext=' Bạn chưa có lớp học ']", 30000, null, "2132dce2-4ee7-4294-8288-c979f2ac9149");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("82684236-7f96-41e0-98ad-b714a2aa6abd")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("82684236-7f96-41e0-98ad-b714a2aa6abd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GiaoBaiTập item.
            /// </summary>
            [RepositoryItem("e6c4041b-816f-44df-9441-3e00afd7bfd6")]
            public virtual Ranorex.SpanTag GiaoBaiTập
            {
                get
                {
                    return _giaobaitậpInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GiaoBaiTập item info.
            /// </summary>
            [RepositoryItemInfo("e6c4041b-816f-44df-9441-3e00afd7bfd6")]
            public virtual RepoItemInfo GiaoBaiTậpInfo
            {
                get
                {
                    return _giaobaitậpInfo;
                }
            }

            /// <summary>
            /// The FaFaUsers item.
            /// </summary>
            [RepositoryItem("85567aed-f504-4e7d-940c-7d5440a3e776")]
            public virtual Ranorex.ITag FaFaUsers
            {
                get
                {
                    return _fafausersInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaUsers item info.
            /// </summary>
            [RepositoryItemInfo("85567aed-f504-4e7d-940c-7d5440a3e776")]
            public virtual RepoItemInfo FaFaUsersInfo
            {
                get
                {
                    return _fafausersInfo;
                }
            }

            /// <summary>
            /// The DivTagBạnChưaCoLớpHọc item.
            /// </summary>
            [RepositoryItem("2132dce2-4ee7-4294-8288-c979f2ac9149")]
            public virtual Ranorex.DivTag DivTagBạnChưaCoLớpHọc
            {
                get
                {
                    return _divtagbạnchưacolớphọcInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagBạnChưaCoLớpHọc item info.
            /// </summary>
            [RepositoryItemInfo("2132dce2-4ee7-4294-8288-c979f2ac9149")]
            public virtual RepoItemInfo DivTagBạnChưaCoLớpHọcInfo
            {
                get
                {
                    return _divtagbạnchưacolớphọcInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
