///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GBT_26
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GBT_26Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("551c892e-d6b2-407d-b70d-e189a0d54498")]
    public partial class GBT_26Repository : RepoGenBaseFolder
    {
        static GBT_26Repository instance = new GBT_26Repository();
        GBT_26RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        GBT_26RepositoryFolders.HọcLiệuSachMềmAppFolder _họcliệusachmềm;

        /// <summary>
        /// Gets the singleton class instance representing the GBT_26Repository element repository.
        /// </summary>
        [RepositoryFolder("551c892e-d6b2-407d-b70d-e189a0d54498")]
        public static GBT_26Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GBT_26Repository() 
            : base("GBT_26Repository", "/", null, 0, false, "551c892e-d6b2-407d-b70d-e189a0d54498", ".\\RepositoryImages\\GBT_26Repository551c892e.rximgres")
        {
            _applicationundertest = new GBT_26RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _họcliệusachmềm = new GBT_26RepositoryFolders.HọcLiệuSachMềmAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("551c892e-d6b2-407d-b70d-e189a0d54498")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("ba136b5c-8919-436b-b7b9-537bce40cba9")]
        public virtual GBT_26RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The HọcLiệuSachMềm folder.
        /// </summary>
        [RepositoryFolder("a5c873a1-1f7e-4f7b-bb98-5f75ac84a018")]
        public virtual GBT_26RepositoryFolders.HọcLiệuSachMềmAppFolder HọcLiệuSachMềm
        {
            get { return _họcliệusachmềm; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class GBT_26RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("ba136b5c-8919-436b-b7b9-537bce40cba9")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, true, "ba136b5c-8919-436b-b7b9-537bce40cba9", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ba136b5c-8919-436b-b7b9-537bce40cba9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ba136b5c-8919-436b-b7b9-537bce40cba9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The HọcLiệuSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("a5c873a1-1f7e-4f7b-bb98-5f75ac84a018")]
        public partial class HọcLiệuSachMềmAppFolder : RepoGenBaseFolder
        {
            GBT_26RepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder _httpshoclieusachmemvnquestionset;
            RepoItemInfo _javascriptvoid0Info;
            RepoItemInfo _divtagsốlầnlamlạiphảilớnhơnhoặcInfo;

            /// <summary>
            /// Creates a new HọcLiệuSachMềm  folder.
            /// </summary>
            public HọcLiệuSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HọcLiệuSachMềm", "/dom[@domain='hoclieu.sachmem.vn']", parentFolder, 30000, null, false, "a5c873a1-1f7e-4f7b-bb98-5f75ac84a018", "")
            {
                _httpshoclieusachmemvnquestionset = new GBT_26RepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder(this);
                _javascriptvoid0Info = new RepoItemInfo(this, "JavascriptVoid0", "body/tag[@tagname='app-root']/div[2]/div//tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div[1]/div[1]/div[2]/a[@href='javascript:void(0)']", 30000, null, "1bf4b1a5-0405-4bdb-9f10-4c6e91018dca");
                _divtagsốlầnlamlạiphảilớnhơnhoặcInfo = new RepoItemInfo(this, "DivTagSốLầnLamLạiPhảiLớnHơnHoặc", ".//div[#'toast-container']/?/?/div[@innertext~'^\\ Số\\ lần\\ làm\\ lại\\ phải\\ lớn\\ ']", 30000, null, "682fc6b3-af6a-4993-9294-e1737d3638a2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a5c873a1-1f7e-4f7b-bb98-5f75ac84a018")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a5c873a1-1f7e-4f7b-bb98-5f75ac84a018")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JavascriptVoid0 item.
            /// </summary>
            [RepositoryItem("1bf4b1a5-0405-4bdb-9f10-4c6e91018dca")]
            public virtual Ranorex.ATag JavascriptVoid0
            {
                get
                {
                    return _javascriptvoid0Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The JavascriptVoid0 item info.
            /// </summary>
            [RepositoryItemInfo("1bf4b1a5-0405-4bdb-9f10-4c6e91018dca")]
            public virtual RepoItemInfo JavascriptVoid0Info
            {
                get
                {
                    return _javascriptvoid0Info;
                }
            }

            /// <summary>
            /// The DivTagSốLầnLamLạiPhảiLớnHơnHoặc item.
            /// </summary>
            [RepositoryItem("682fc6b3-af6a-4993-9294-e1737d3638a2")]
            public virtual Ranorex.DivTag DivTagSốLầnLamLạiPhảiLớnHơnHoặc
            {
                get
                {
                    return _divtagsốlầnlamlạiphảilớnhơnhoặcInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagSốLầnLamLạiPhảiLớnHơnHoặc item info.
            /// </summary>
            [RepositoryItemInfo("682fc6b3-af6a-4993-9294-e1737d3638a2")]
            public virtual RepoItemInfo DivTagSốLầnLamLạiPhảiLớnHơnHoặcInfo
            {
                get
                {
                    return _divtagsốlầnlamlạiphảilớnhơnhoặcInfo;
                }
            }

            /// <summary>
            /// The HttpsHoclieuSachmemVnQuestionSet folder.
            /// </summary>
            [RepositoryFolder("52c418c1-fdd6-4f5f-b3e8-5128fdaf6893")]
            public virtual GBT_26RepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder HttpsHoclieuSachmemVnQuestionSet
            {
                get { return _httpshoclieusachmemvnquestionset; }
            }
        }

        /// <summary>
        /// The HttpsHoclieuSachmemVnQuestionSetFolder folder.
        /// </summary>
        [RepositoryFolder("52c418c1-fdd6-4f5f-b3e8-5128fdaf6893")]
        public partial class HttpsHoclieuSachmemVnQuestionSetFolder : RepoGenBaseFolder
        {
            RepoItemInfo _submitInfo;
            RepoItemInfo _ngoptionngoptionmarkedInfo;
            RepoItemInfo _nginputInfo;
            RepoItemInfo _numberInfo;

            /// <summary>
            /// Creates a new HttpsHoclieuSachmemVnQuestionSet  folder.
            /// </summary>
            public HttpsHoclieuSachmemVnQuestionSetFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsHoclieuSachmemVnQuestionSet", ".//div[#'createAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b18b248150cd8b90656fe/5a4b18b248150cd8b9065701/preview']", parentFolder, 30000, null, false, "52c418c1-fdd6-4f5f-b3e8-5128fdaf6893", "")
            {
                _submitInfo = new RepoItemInfo(this, "Submit", "?/?/input[@type='submit']", 30000, null, "b2459964-f2dd-4fd1-a8db-347663b34570");
                _ngoptionngoptionmarkedInfo = new RepoItemInfo(this, "NgOptionNgOptionMarked", "div[1]/div[3]/?/?/tag[@tagname='ng-dropdown-panel']/div/div[2]/div", 30000, null, "39b9e9ce-9320-43d0-8768-f22674455d90");
                _nginputInfo = new RepoItemInfo(this, "NgInput", "div[1]/div[3]/tag[@tagname='ng-select']/div/div/div[2]", 30000, null, "6c75e94c-0135-487d-971f-4083624539c6");
                _numberInfo = new RepoItemInfo(this, "Number", "div[1]/div[7]/input[@type='number']", 30000, null, "4cc19920-4895-4109-b373-a44aecc5f027");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("52c418c1-fdd6-4f5f-b3e8-5128fdaf6893")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("52c418c1-fdd6-4f5f-b3e8-5128fdaf6893")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("b2459964-f2dd-4fd1-a8db-347663b34570")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("b2459964-f2dd-4fd1-a8db-347663b34570")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarked item.
            /// </summary>
            [RepositoryItem("39b9e9ce-9320-43d0-8768-f22674455d90")]
            public virtual Ranorex.DivTag NgOptionNgOptionMarked
            {
                get
                {
                    return _ngoptionngoptionmarkedInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarked item info.
            /// </summary>
            [RepositoryItemInfo("39b9e9ce-9320-43d0-8768-f22674455d90")]
            public virtual RepoItemInfo NgOptionNgOptionMarkedInfo
            {
                get
                {
                    return _ngoptionngoptionmarkedInfo;
                }
            }

            /// <summary>
            /// The NgInput item.
            /// </summary>
            [RepositoryItem("6c75e94c-0135-487d-971f-4083624539c6")]
            public virtual Ranorex.DivTag NgInput
            {
                get
                {
                    return _nginputInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgInput item info.
            /// </summary>
            [RepositoryItemInfo("6c75e94c-0135-487d-971f-4083624539c6")]
            public virtual RepoItemInfo NgInputInfo
            {
                get
                {
                    return _nginputInfo;
                }
            }

            /// <summary>
            /// The Number item.
            /// </summary>
            [RepositoryItem("4cc19920-4895-4109-b373-a44aecc5f027")]
            public virtual Ranorex.InputTag Number
            {
                get
                {
                    return _numberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Number item info.
            /// </summary>
            [RepositoryItemInfo("4cc19920-4895-4109-b373-a44aecc5f027")]
            public virtual RepoItemInfo NumberInfo
            {
                get
                {
                    return _numberInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
