///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GBT_26
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenBrowser recording.
    /// </summary>
    [TestModule("fbf13950-6643-49e0-b371-20c40be1fb34", ModuleType.Recording, 1)]
    public partial class OpenBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GBT_26Repository repository.
        /// </summary>
        public static GBT_26Repository repo = GBT_26Repository.Instance;

        static OpenBrowser instance = new OpenBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenBrowser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenBrowser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://hoclieu.sachmem.vn/question_set/5a4b18b248150cd8b90656fe/5a4b18b248150cd8b9065701/preview' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://hoclieu.sachmem.vn/question_set/5a4b18b248150cd8b90656fe/5a4b18b248150cd8b9065701/preview", "chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.JavascriptVoid0' at 27;20.", repo.HọcLiệuSachMềm.JavascriptVoid0Info, new RecordItemIndex(1));
            repo.HọcLiệuSachMềm.JavascriptVoid0.Click("27;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgInput' at 127;5.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgInputInfo, new RecordItemIndex(2));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgInput.Click("127;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgOptionNgOptionMarked' at 126;9.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgOptionNgOptionMarkedInfo, new RecordItemIndex(3));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgOptionNgOptionMarked.Click("126;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(4));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number' at 103;11.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(5));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number.Click("103;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '-10' with focus on 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number'.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(6));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number.PressKeys("-10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Submit' at 33;12.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.SubmitInfo, new RecordItemIndex(7));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Submit.Click("33;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'HọcLiệuSachMềm.DivTagSốLầnLamLạiPhảiLớnHơnHoặc'.", repo.HọcLiệuSachMềm.DivTagSốLầnLamLạiPhảiLớnHơnHoặcInfo, new RecordItemIndex(8));
            Validate.Exists(repo.HọcLiệuSachMềm.DivTagSốLầnLamLạiPhảiLớnHơnHoặcInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
